""" Settings and constants """

HOST_ADDRESS = "127.0.0.1", 2779  # Original: 2775
LOG_ADDRESS = "127.0.0.1", 2780   # Original: 2776
HOST_STOP_COMMAND = "STOP_SERVER"
LOG_STOP_COMMAND = "STOP_SERVER"
CONNECTED_COMMAND = "CONNECTED"
DISCONNECT_COMMAND = "CLOSE_CONNECTION"
STRUCT_PACK_FORMAT = ">I"
MAX_PROCESS_COUNT = 4
